// <auto-generated />
using EventPatternMatching.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EventPatternMatching.Migrations
{
    [DbContext(typeof(EventPatternMatchingContext))]
    [Migration("20170906151628_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("EventPatternMatching.Models.EventPatternMatching", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<string>("DeviceId");

                    b.HasKey("ID");

                    b.ToTable("EventPatternMatching");
                });
#pragma warning restore 612, 618
        }
    }
}
